#spring.application.name=Spring-data-JPA-ex


spring.datasource.url=jdbc:postgresql://localhost:5432/STARK
spring.datasource.username=postgres
spring.datasource.password=11223344
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
